# Generated by Django 5.0.4 on 2024-04-14 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('idClass', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('idSubject', models.AutoField(primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('idClass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.classes')),
                ('idUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.users')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('idStudent', models.AutoField(primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=100)),
                ('gradeGroup', models.CharField(max_length=100)),
                ('fatherEducation', models.IntegerField(choices=[(1, 'Primaria y secundaria'), (2, 'Media superior'), (3, 'Superior o mayor')])),
                ('motherEducation', models.IntegerField(choices=[(1, 'Primaria y secundaria'), (2, 'Media superior'), (3, 'Superior o mayor')])),
                ('familyIncome', models.IntegerField(choices=[(1, '< 5000'), (2, '5000 - 10000'), (3, '> 10000')])),
                ('highSchoolGPA', models.IntegerField(choices=[(1, '< 7.5'), (2, '7.5 - 8.5'), (3, '> 8.5')])),
                ('defaultedSubjects', models.IntegerField(choices=[(1, '0'), (2, '1'), (3, '> 2')])),
                ('currentGPA', models.FloatField()),
                ('studyPreference', models.IntegerField(choices=[(1, 'Solo'), (2, 'Con otra persona'), (3, 'En grupo')])),
                ('preferenceAcademicActivities', models.IntegerField(choices=[(1, 'Solo'), (2, 'Con otra persona'), (3, 'En grupo')])),
                ('studyFrecuency', models.IntegerField(choices=[(1, 'Diario'), (2, 'Una semana antes de un examen'), (3, 'Un día antes de un examen')])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('idClass', models.ManyToManyField(blank=True, to='model.classes')),
                ('idSubject', models.ManyToManyField(blank=True, to='model.subjects')),
                ('idUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.users')),
            ],
        ),
        migrations.CreateModel(
            name='Tendencys',
            fields=[
                ('idTendency', models.AutoField(primary_key=True, serialize=False)),
                ('studentClass', models.IntegerField()),
                ('tendencyToFail', models.FloatField()),
                ('tendencyToApprove', models.FloatField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('idStudent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.students')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='idUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.users'),
        ),
    ]
