# Generated by Django 5.0.4 on 2024-04-16 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_rename_classes_class_rename_students_student_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tendencys',
            new_name='Tendency',
        ),
        migrations.AlterModelTable(
            name='class',
            table='class',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subject',
        ),
        migrations.AlterModelTable(
            name='tendency',
            table='tendency',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
