# Generated by Django 5.0.4 on 2024-05-03 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_rename_classname_class_class_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='id_class',
            new_name='clas',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='id_subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='id_class',
            new_name='clas',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tendency',
            old_name='id_student',
            new_name='student',
        ),
    ]
