# Generated by Django 5.0.4 on 2024-05-03 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_rename_id_user_class_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='study_frecuency',
            new_name='study_frequency',
        ),
    ]
