# Generated by Django 5.0.4 on 2024-05-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_alter_student_clas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tendency',
            name='tendency_to_approve',
        ),
        migrations.RemoveField(
            model_name='tendency',
            name='tendency_to_fail',
        ),
        migrations.AddField(
            model_name='tendency',
            name='tendency',
            field=models.IntegerField(choices=[(1, '0'), (2, '1'), (3, '2 o mas')], default=1),
        ),
    ]
