# Generated by Django 5.0.4 on 2024-05-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_remove_tendency_tendency_to_approve_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tendency',
            name='student_class',
        ),
    ]
