# Generated by Django 5.0.4 on 2024-05-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0012_remove_tendency_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendency',
            name='student_class',
            field=models.CharField(default='1-01', max_length=100),
        ),
    ]
