# Generated by Django 5.0.4 on 2024-05-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0014_alter_tendency_student_class_alter_tendency_tendency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tendency',
            name='tendency',
            field=models.CharField(default='0', max_length=16),
        ),
    ]
